import os
import re
from functools import lru_cache
from urllib.parse import urlsplit, urlunsplit

import pandas as pd
from sqlalchemy import create_engine, text
from sqlalchemy.engine import Engine

try:
    import streamlit as st
except Exception:
    st = None


def _get_database_url() -> str:
    def _normalize_database_url(raw_url: str) -> str:
        normalized = raw_url.strip()
        parts = urlsplit(normalized)

        # Common typo: password contains %40, but the auth/host '@' delimiter is missing.
        if parts.scheme.startswith("postgres") and "@" not in parts.netloc and "%40" in parts.netloc:
            netloc = parts.netloc
            split_index = netloc.rfind("%40")
            if split_index != -1:
                netloc = f"{netloc[:split_index + 3]}@{netloc[split_index + 3:]}"
                normalized = urlunsplit((parts.scheme, netloc, parts.path, parts.query, parts.fragment))
                parts = urlsplit(normalized)

        if not parts.scheme.startswith("postgres") or not parts.hostname:
            raise RuntimeError(
                "DATABASE_URL is invalid. Expected format: postgresql://user:password@host:5432/dbname"
            )

        if parts.scheme in {"postgresql", "postgres"}:
            normalized = urlunsplit(("postgresql+psycopg", parts.netloc, parts.path, parts.query, parts.fragment))

        return normalized

    if st is not None and "DATABASE_URL" in st.secrets:
        return _normalize_database_url(str(st.secrets["DATABASE_URL"]))

    database_url = os.getenv("DATABASE_URL")
    if database_url:
        return _normalize_database_url(database_url)

    raise RuntimeError("DATABASE_URL is missing. Set it in .streamlit/secrets.toml or environment variables.")


def _migrate_schema(engine: Engine) -> None:
    with engine.begin() as conn:
        lower_with_space_exists = conn.execute(
            text(
                """
                SELECT EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'data'
                      AND column_name = 'Lower '
                )
                """
            )
        ).scalar_one()

        lower_exists = conn.execute(
            text(
                """
                SELECT EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'data'
                      AND column_name = 'Lower'
                )
                """
            )
        ).scalar_one()

        if lower_with_space_exists and not lower_exists:
            conn.execute(text('ALTER TABLE "data" RENAME COLUMN "Lower " TO "Lower"'))

        entry_id_exists = conn.execute(
            text(
                """
                SELECT EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'data'
                      AND column_name = 'EntryId'
                )
                """
            )
        ).scalar_one()

        if not entry_id_exists:
            conn.execute(text('ALTER TABLE "data" ADD COLUMN "EntryId" BIGINT GENERATED BY DEFAULT AS IDENTITY'))
            conn.execute(text('UPDATE "data" SET "EntryId" = DEFAULT WHERE "EntryId" IS NULL'))
            conn.execute(text('CREATE UNIQUE INDEX IF NOT EXISTS data_entryid_uidx ON "data" ("EntryId")'))


def _mask_sensitive_details(message: str) -> str:
    masked = re.sub(r"://[^@\s]+@", "://***:***@", message)
    masked = re.sub(r"(?i)(password\s*=\s*)[^\s,;]+", r"\1***", masked)
    return masked


@lru_cache(maxsize=1)
def _connect_db() -> Engine:
    engine = create_engine(_get_database_url(), pool_pre_ping=True)
    _migrate_schema(engine)
    return engine


def check_db_connection() -> tuple[bool, str]:
    try:
        engine = _connect_db()
        with engine.connect() as conn:
            conn.execute(text('SELECT 1'))
        return True, "Connected to Supabase Postgres"
    except Exception as exc:
        return False, f"Database connection failed: {_mask_sensitive_details(str(exc))}"


def save_data(entry_date: str, upper: int, lower: int, bpm: int) -> None:
    engine = _connect_db()
    with engine.begin() as conn:
        conn.execute(
            text('INSERT INTO "data" ("Date", "Upper", "Lower", "BPM") VALUES (:entry_date, :upper, :lower, :bpm)'),
            {"entry_date": entry_date, "upper": upper, "lower": lower, "bpm": bpm},
        )


def update_data(entry_id: int, entry_date: str, upper: int, lower: int, bpm: int) -> None:
    engine = _connect_db()
    with engine.begin() as conn:
        conn.execute(
            text(
                'UPDATE "data" SET "Date" = :entry_date, "Upper" = :upper, "Lower" = :lower, "BPM" = :bpm WHERE "EntryId" = :entry_id'
            ),
            {"entry_date": entry_date, "upper": upper, "lower": lower, "bpm": bpm, "entry_id": entry_id},
        )


def delete_data(entry_id: int) -> None:
    engine = _connect_db()
    with engine.begin() as conn:
        conn.execute(text('DELETE FROM "data" WHERE "EntryId" = :entry_id'), {"entry_id": entry_id})


def load_data() -> pd.DataFrame:
    engine = _connect_db()
    df = pd.read_sql_query(
        text('SELECT "EntryId", "Date", "Upper", "Lower", "BPM" FROM "data"'),
        engine,
    )
    return df